# **PUNTO DE REORDEN**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/# Modelo “probabilizado” de cantidad económica de pedido.xlsx",sheet_name="Sheet1")
data

D      sigma  L     alpha  punto_reorden  Stock de seguridad
0     103.148510  29.553225  1  0.038716     155.333287           52.184777
1     105.700065  23.341299  6  0.081145     714.096389           79.896000
2     100.634482  36.368711  2  0.085674     271.623583           70.354619
3      84.720857  23.644572  5  0.036265     518.548477           94.944194
4     104.661577  21.493302  3  0.015154     394.621058           80.636326
...          ...        ... ..       ...            ...                 ...
9995   89.324660  20.515150  8  0.028272     825.241979          110.644698
9996  112.144468  33.557739  2  0.092521     287.189063           62.900126
9997  104.183425  29.980936  1  0.023514     163.727238           59.543813
9998  103.145191  38.389679  8  0.038666    1016.958969          191.797438
9999   83.915849  36.924664  5  0.015276     598.158764          178.579521

[10000 rows x 6 columns]

In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D",	"sigma",	"L"	,"alpha"]]
y = data["punto_reorden"]
X.shape

(10000, 4)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(4,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(32,activation = "relu"))
model.add(Dense(32,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
optimizer = Adam(learning_rate=0.001)  # Reducimos la tasa de aprendizaje
model.compile(optimizer=optimizer, loss="mae", metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 1000
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.5987 - mae: 2.5987
Error:2.641618013381958, Métrica: 2.641618013381958


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


Predicciones       Reales
0       256.855499   254.825160
1       993.042236   990.752547
2      1186.179810  1185.445486
3       740.786255   739.422644
4      1024.054443  1024.485067
...            ...          ...
1995    145.789673   146.054754
1996   1005.235168  1010.064233
1997   1060.971069  1062.532897
1998    430.704834   430.420033
1999    905.209167   908.260803

[2000 rows x 2 columns]

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 4)                   │              20 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 32)                  │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 32)                  │           1,056 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,809 (14.88 KB)

 Trainable params: 1,269 (4.96 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,540 (9.93 KB)

In [ ]:
X_test

array([[ 0.29431414, -1.71815035, -1.23028663, -0.37712713],
       [-1.38516666, -0.06441716,  1.57308661,  0.07697251],
       [ 1.39881936,  0.23278806,  1.22266496,  0.42129007],
       ...,
       [ 0.04064834,  0.68535099,  1.22266496,  0.20657376],
       [ 1.36256863,  0.32254685, -0.87986497,  0.3601458 ],
       [-1.05441369, -1.53238384,  1.22266496, -0.81791015]])

In [ ]:
nuevo = model.predict(np.array(sc.transform([[174,	33	, 1 ,	0.018]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
nuevo

array([[478.43784]], dtype=float32)

# **STOCK DE SEGURIDAD**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [ ]:
data = pd.read_excel("/content/drive/MyDrive/# Modelo “probabilizado” de cantidad económica de pedido.xlsx",sheet_name="Sheet1")
data

D      sigma  L     alpha  punto_reorden  Stock de seguridad
0     103.148510  29.553225  1  0.038716     155.333287           52.184777
1     105.700065  23.341299  6  0.081145     714.096389           79.896000
2     100.634482  36.368711  2  0.085674     271.623583           70.354619
3      84.720857  23.644572  5  0.036265     518.548477           94.944194
4     104.661577  21.493302  3  0.015154     394.621058           80.636326
...          ...        ... ..       ...            ...                 ...
9995   89.324660  20.515150  8  0.028272     825.241979          110.644698
9996  112.144468  33.557739  2  0.092521     287.189063           62.900126
9997  104.183425  29.980936  1  0.023514     163.727238           59.543813
9998  103.145191  38.389679  8  0.038666    1016.958969          191.797438
9999   83.915849  36.924664  5  0.015276     598.158764          178.579521

[10000 rows x 6 columns]

In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D",	"sigma",	"L"	,"alpha"]]
y = data["Stock de seguridad"]
X.shape

(10000, 4)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(4,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(16,activation = "relu"))
model.add(Dense(16,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
model.compile(optimizer="adam",loss = "mse",metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 100
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/100
Epoch 2/100
Epoch 3/100
Epoch 4/100
Epoch 5/100
Epoch 6/100
Epoch 7/100
Epoch 8/100
Epoch 9/100
Epoch 10/100
Epoch 11/100
Epoch 12/100
Epoch 13/100
Epoch 14/100
Epoch 15/100
Epoch 16/100
Epoch 17/100
Epoch 18/100
Epoch 19/100
Epoch 20/100
Epoch 21/100
Epoch 22/100
Epoch 23/100
Epoch 24/100
Epoch 25/100
Epoch 26/100
Epoch 27/100
Epoch 28/100
Epoch 29/100
Epoch 30/100
Epoch 31/100
Epoch 32/100
Epoch 33/100
Epoch 34/100
Epoch 35/100
Epoch 36/100
Epoch 37/100
Epoch 38/100
Epoch 39/100
Epoch 40/100
Epoch 41/100
Epoch 42/100
Epoch 43/100
Epoch 44/100
Epoch 45/100
Epoch 46/100
Epoch 47/100
Epoch 48/100
Epoch 49/100
Epoch 50/100
Epoch 51/100
Epoch 52/100
Epoch 53/100
Epoch 54/100
Epoch 55/100
Epoch 56/100
Epoch 57/100
Epoch 58/100
Epoch 59/100
Epoch 60/100
Epoch 61/100
Epoch 62/100
Epoch 63/100
Epoch 64/100
Epoch 65/100
Epoch 66/100
Epoch 67/100
Epoch 68/100
Epoch 69/100
Epoch 70/100
Epoch 71/100
Epoch 72/100
Epoch 73/100
Epoch 74/100
Epoch 75/100
Epoch 76/100
Epoch 77/100
Epoch 78

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50.9719 - mae: 5.3860
Error:54.087196350097656, Métrica: 5.4563889503479


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


Predicciones      Reales
0        47.564842   47.950706
1       155.442871  147.641464
2       143.631821  141.306362
3       117.578148  115.314133
4       151.797729  142.566597
...            ...         ...
1995     86.263397   65.698872
1996    103.590675   95.584213
1997    158.821716  157.596830
1998     75.618515   83.612141
1999    124.737160  115.560956

[2000 rows x 2 columns]

In [ ]:
y_test

6252     47.950706
4684    147.641464
1731    141.306362
4742    115.314133
4521    142.566597
           ...    
6412     65.698872
8285     95.584213
7853    157.596830
1095     83.612141
6929    115.560956
Name: Stock de seguridad, Length: 2000, dtype: float64

In [ ]:
X_test

array([[ 0.30180676, -1.73642876, -1.19568759, -0.36636103],
       [-1.34887244, -0.08892882,  1.59186908,  0.08340014],
       [ 1.38737069,  0.20715617,  1.24342449,  0.42442808],
       ...,
       [ 0.05249109,  0.65801331,  1.24342449,  0.21176318],
       [ 1.35174163,  0.29657665, -0.847243  ,  0.36386799],
       [-1.0237916 , -1.55136244,  1.24342449, -0.80293281]])

In [ ]:
nuevo = model.predict(np.array(sc.transform([[2,	121	,27,	0.044]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


In [ ]:
nuevo

array([[104.28033]], dtype=float32)