# **Cantidad pedida**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/Modelos de inventarios.xlsx",sheet_name="M_política_s-S")
data

x      k      c      h      p  D_max       S      s1       s2  \
0    5  24.72   2.04   2.86  18.30     94   7.680  17.270   -1.910   
1   29  63.19   4.54   0.78  12.20     26  15.340  31.630    0.280   
2   21  46.50   8.61   3.81  14.29     20   6.270  16.470   -3.850   
3    6  30.32   3.95   3.08   6.46     23   6.050  18.580   -6.030   
4   22  59.36   5.29   4.88  12.96     12   5.150  14.130   -3.770   
5   30  78.71   4.27   1.76  15.90     73  48.070  74.070   22.840   
6   24  62.23   4.42   2.67   6.10     70  13.400  45.220  -18.130   
7    3  26.39   4.30   7.30  13.13     10   4.320   9.410   -0.760   
8   13  58.77   1.37   3.09   6.90     50  27.670  56.450    4.980   
9   15  26.97   8.26   3.17  13.13     63  18.820  33.330    4.410   
10   6  48.40   8.69   4.95  16.30     60  21.480  38.030    4.960   
11   3  17.19   4.69   4.36  26.27     75  52.840  62.010   43.660   
12  13  40.41   3.70   3.96   9.86     10   4.450  17.940   -7.010   
13  13  25.20   5.74   3.67  14.14     13   6.130  12.280    0.060   
14  16  23.70   8.13   2.39  10.00     28   4.220  14.620   -6.120   
15  10  57.69   4.53   3.06  11.14     68  31.650  57.100    8.990   
16  19  76.04   8.06   1.56   9.53    100  13.250  50.540  -23.810   
17  26  48.26   1.94   0.83   1.82     59  50.410  67.810   33.180   
18  22  84.07   3.14   2.08  13.26     55  36.280  64.480   13.350   
19  21  50.66   5.45   3.88  28.00     54  38.190  52.110   25.640   
20  50  84.07   6.73   0.64  25.00     97  69.110  95.720   44.810   
21  16  92.50   9.78   0.57  31.72     10   6.790  14.390   -0.760   
22   8  17.47   3.60   4.62   4.58     16   1.700   9.530   -6.110   
23  29  91.56   0.74   3.61  15.13      3   7.710   9.920   -5.290   
24  11  36.45   8.81   4.93  19.76     94   4.430  82.520    0.870   
25  19  21.00   0.10   2.00   6.50      5   3.760  75.430   -0.153   
26   7  52.00   9.80   1.70  16.00     35  15.170  26.890   -2.370   
27  21  37.00   8.00   1.80  11.00     52  12.180  29.520   -5.150   
28  14  84.00   5.00   4.40   7.00     37   6.490  30.330  -16.990   
29  15  18.00   8.00   0.50  22.00     89  60.760  73.490   48.450   
30  10  98.00   6.00   0.10  12.50     65  33.530  65.330    1.730   
31   2  63.00   5.00   3.50  19.00     39  10.100  44.810    3.790   
32   8  71.00   9.00   1.50  20.00     96  50.280  74.320   23.910   
33  18  10.00   1.50   1.50   8.00     60  45.160  56.950   33.370   
34  13  19.00   7.00   1.80  19.50      5   2.930   5.920   -0.050   
35  21  44.00   7.00   1.30  30.00     85  62.460  77.920   47.003   
36   8  28.00   6.00   4.10  33.00     43  31.290  39.350   23.230   
37  17  86.00   8.00   2.00   9.40     45   5.530  31.590  -20.530   
38   9  15.00   4.50   1.20  13.00     62  37.100  48.560   25.660   
39  15  48.00   2.00   1.90   7.00     85  47.750  78.036   17.470   
40  10  49.00   1.30   2.30  17.00     29  23.590  50.620 -344.000   
41  11  60.00   6.00   3.50  15.00     84  40.860  64.210   17.520   
42  24  81.00   8.00   1.40  18.00     17   8.760  20.670   -3.150   
43   5  93.00   7.00   0.40  11.50     75  28.360  -3.850    9.530   
44  19  88.00   1.80   3.20   7.00     10   5.090  18.230   -8.030   
45   6  31.00   7.00   1.10  72.00     14   5.340  13.480   -2.790   
46  26  31.00  20.00  21.00  26.00     18   3.840  10.145   -2.450   
47  17  11.00   8.40   1.30  10.40     48   8.205  17.700   -1.290   
48   5  51.00   3.00   2.50  12.00     55  34.130  53.810   14.460   
49  21  58.00   4.00   0.40  12.00     92  59.350  88.690   30.010   

   cantidad_pedido  
0         No pedir  
1         No pedir  
2         No pedir  
3         No pedir  
4         No pedir  
5            Pedir  
6         No pedir  
7         No pedir  
8            Pedir  
9            Pedir  
10           Pedir  
11           Pedir  
12        No pedir  
13        No pedir  
14        No pedir  
15           Pedir  
16        No pedir  
17           Pedir  
18           Pedir  
19           P

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
mode_ship_label = {value: key for key,value in enumerate(data["cantidad_pedido"].unique())}

In [ ]:
data["cantidad_pedido"] = data["cantidad_pedido"].map(mode_ship_label)

In [ ]:
data

x      k      c      h      p  D_max       S      s1       s2  \
0    5  24.72   2.04   2.86  18.30     94   7.680  17.270   -1.910   
1   29  63.19   4.54   0.78  12.20     26  15.340  31.630    0.280   
2   21  46.50   8.61   3.81  14.29     20   6.270  16.470   -3.850   
3    6  30.32   3.95   3.08   6.46     23   6.050  18.580   -6.030   
4   22  59.36   5.29   4.88  12.96     12   5.150  14.130   -3.770   
5   30  78.71   4.27   1.76  15.90     73  48.070  74.070   22.840   
6   24  62.23   4.42   2.67   6.10     70  13.400  45.220  -18.130   
7    3  26.39   4.30   7.30  13.13     10   4.320   9.410   -0.760   
8   13  58.77   1.37   3.09   6.90     50  27.670  56.450    4.980   
9   15  26.97   8.26   3.17  13.13     63  18.820  33.330    4.410   
10   6  48.40   8.69   4.95  16.30     60  21.480  38.030    4.960   
11   3  17.19   4.69   4.36  26.27     75  52.840  62.010   43.660   
12  13  40.41   3.70   3.96   9.86     10   4.450  17.940   -7.010   
13  13  25.20   5.74   3.67  14.14     13   6.130  12.280    0.060   
14  16  23.70   8.13   2.39  10.00     28   4.220  14.620   -6.120   
15  10  57.69   4.53   3.06  11.14     68  31.650  57.100    8.990   
16  19  76.04   8.06   1.56   9.53    100  13.250  50.540  -23.810   
17  26  48.26   1.94   0.83   1.82     59  50.410  67.810   33.180   
18  22  84.07   3.14   2.08  13.26     55  36.280  64.480   13.350   
19  21  50.66   5.45   3.88  28.00     54  38.190  52.110   25.640   
20  50  84.07   6.73   0.64  25.00     97  69.110  95.720   44.810   
21  16  92.50   9.78   0.57  31.72     10   6.790  14.390   -0.760   
22   8  17.47   3.60   4.62   4.58     16   1.700   9.530   -6.110   
23  29  91.56   0.74   3.61  15.13      3   7.710   9.920   -5.290   
24  11  36.45   8.81   4.93  19.76     94   4.430  82.520    0.870   
25  19  21.00   0.10   2.00   6.50      5   3.760  75.430   -0.153   
26   7  52.00   9.80   1.70  16.00     35  15.170  26.890   -2.370   
27  21  37.00   8.00   1.80  11.00     52  12.180  29.520   -5.150   
28  14  84.00   5.00   4.40   7.00     37   6.490  30.330  -16.990   
29  15  18.00   8.00   0.50  22.00     89  60.760  73.490   48.450   
30  10  98.00   6.00   0.10  12.50     65  33.530  65.330    1.730   
31   2  63.00   5.00   3.50  19.00     39  10.100  44.810    3.790   
32   8  71.00   9.00   1.50  20.00     96  50.280  74.320   23.910   
33  18  10.00   1.50   1.50   8.00     60  45.160  56.950   33.370   
34  13  19.00   7.00   1.80  19.50      5   2.930   5.920   -0.050   
35  21  44.00   7.00   1.30  30.00     85  62.460  77.920   47.003   
36   8  28.00   6.00   4.10  33.00     43  31.290  39.350   23.230   
37  17  86.00   8.00   2.00   9.40     45   5.530  31.590  -20.530   
38   9  15.00   4.50   1.20  13.00     62  37.100  48.560   25.660   
39  15  48.00   2.00   1.90   7.00     85  47.750  78.036   17.470   
40  10  49.00   1.30   2.30  17.00     29  23.590  50.620 -344.000   
41  11  60.00   6.00   3.50  15.00     84  40.860  64.210   17.520   
42  24  81.00   8.00   1.40  18.00     17   8.760  20.670   -3.150   
43   5  93.00   7.00   0.40  11.50     75  28.360  -3.850    9.530   
44  19  88.00   1.80   3.20   7.00     10   5.090  18.230   -8.030   
45   6  31.00   7.00   1.10  72.00     14   5.340  13.480   -2.790   
46  26  31.00  20.00  21.00  26.00     18   3.840  10.145   -2.450   
47  17  11.00   8.40   1.30  10.40     48   8.205  17.700   -1.290   
48   5  51.00   3.00   2.50  12.00     55  34.130  53.810   14.460   
49  21  58.00   4.00   0.40  12.00     92  59.350  88.690   30.010   

    cantidad_pedido  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
5                 1  
6                 0  
7                 0  
8                 1  
9                 1  
10                1  
11                1  
12                0  
13                0  
14                0  
15                1  
16                0  
17                1  
18              

In [ ]:
X = np.asarray([data["x"],
                      data["k"],
                      data["c"],
                      data["h"],
                      data["p"],
                      data["D_max"],
                      data["S"],
                      data["s1"],
                      data["s2"]])

In [ ]:
X = X.T

In [ ]:
X

array([[ 5.0000e+00,  2.4720e+01,  2.0400e+00,  2.8600e+00,  1.8300e+01,
         9.4000e+01,  7.6800e+00,  1.7270e+01, -1.9100e+00],
       [ 2.9000e+01,  6.3190e+01,  4.5400e+00,  7.8000e-01,  1.2200e+01,
         2.6000e+01,  1.5340e+01,  3.1630e+01,  2.8000e-01],
       [ 2.1000e+01,  4.6500e+01,  8.6100e+00,  3.8100e+00,  1.4290e+01,
         2.0000e+01,  6.2700e+00,  1.6470e+01, -3.8500e+00],
       [ 6.0000e+00,  3.0320e+01,  3.9500e+00,  3.0800e+00,  6.4600e+00,
         2.3000e+01,  6.0500e+00,  1.8580e+01, -6.0300e+00],
       [ 2.2000e+01,  5.9360e+01,  5.2900e+00,  4.8800e+00,  1.2960e+01,
         1.2000e+01,  5.1500e+00,  1.4130e+01, -3.7700e+00],
       [ 3.0000e+01,  7.8710e+01,  4.2700e+00,  1.7600e+00,  1.5900e+01,
         7.3000e+01,  4.8070e+01,  7.4070e+01,  2.2840e+01],
       [ 2.4000e+01,  6.2230e+01,  4.4200e+00,  2.6700e+00,  6.1000e+00,
         7.0000e+01,  1.3400e+01,  4.5220e+01, -1.8130e+01],
       [ 3.0000e+00,  2.6390e+01,  4.3000e+00,  7.3000e+00,  1

In [ ]:
y = np.asarray(data["cantidad_pedido"])

In [ ]:
y

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [ ]:
X_train.shape,X_test.shape, y_train.shape

((37, 9), (13, 9), (37,))

In [ ]:
##Escalar los datos

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
from threading import active_count
import tensorflow as tf

## input layer  9 neurons
inputlyr = tf.keras.layers.Dense(units = 9)

## hidden layers with ReLU
hdnlyr01 = tf.keras.layers.Dense(units = 16, activation = tf.nn.relu)
hdnlyr02 = tf.keras.layers.Dense(units = 16, activation = tf.nn.relu)

## output layer
outputlyr = tf.keras.layers.Dense(units = 2, activation = tf.nn.softmax)

## Crear la NN

model = tf.keras.Sequential([inputlyr,hdnlyr01,hdnlyr02,outputlyr])

In [ ]:
model.compile(
    optimizer = tf.keras.optimizers.Adam(),
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics = ["accuracy"]

)

In [ ]:
test_loss, test_acc = model.evaluate(X_test,y_test,verbose = 2)
print("\nTrain accuracy:", test_acc)

1/1 - 1s - 738ms/step - accuracy: 0.6923 - loss: 0.6146

Train accuracy: 0.692307710647583


In [ ]:
predictions = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step


In [ ]:
predictions[10]

array([0.66687673, 0.3331232 ], dtype=float32)

In [ ]:
sum(predictions[10])

0.9999999403953552

In [ ]:
np.argmax(predictions[10])

0

In [ ]:
y_test[10]

0

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 9)                   │              90 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 2)                   │              34 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 556 (2.17 KB)

 Trainable params: 556 (2.17 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
nuevo = model.predict(np.array(sc.fit_transform([[5,	24.72,	2.04,	2.86,	18.30,	94,	7.680,	17.270,	-1.910]])))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


In [ ]:
nuevo

array([[0.5, 0.5]], dtype=float32)

In [ ]:
np.argmax(nuevo)


0