# **Cantidad pedida**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/simulacion_eoq.xlsx",sheet_name="Sheet1")
data


D          K         h  L  Cantidad a pedir  Punto de reorden
0     602  53.193988  4.803646  5        115.467304          7.850101
1     935  65.869443  1.828454  2        259.549855         53.151016
2     848  61.015955  3.847163  2        164.007729         55.922705
3     770  75.765259  3.969524  4        171.445553        165.425592
4     606  55.118354  2.992482  4        149.411372         33.418055
...   ...        ...       ... ..               ...               ...
9985  556  55.581834  3.269109  6        137.500443         35.989359
9986  611  72.051740  1.716667  2        226.472121         89.639394
9987  504  67.693537  2.971393  2        151.538789         98.767265
9988  909  61.165752  4.494511  9        157.293176          1.754837
9989  913  82.108971  4.093853  2        191.372515        103.647361

[9990 rows x 6 columns]

In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D","K","h","L"]]
y = data["Cantidad a pedir"]
X.shape

(9990, 4)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(4,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(32,activation = "relu"))
model.add(Dense(32,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida



/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
model.compile(optimizer="adam",loss = "mse",metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 1000
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.5085 - mae: 0.9108
Error:1.451123595237732, Métrica: 0.9024146795272827


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


Predicciones      Reales
0       205.329575  205.211415
1       159.172226  160.250764
2       128.211899  129.160170
3       214.154877  211.978780
4       251.412354  252.911653
...            ...         ...
1993    157.848984  157.525233
1994    318.768982  318.751412
1995    232.837967  233.971520
1996    206.192703  206.957055
1997    134.570312  135.205970

[1998 rows x 2 columns]

In [ ]:
y_test

4022    205.211415
5412    160.250764
487     129.160170
39      211.978780
6795    252.911653
           ...    
7292    157.525233
7710    318.751412
4094    233.971520
3944    206.957055
8256    135.205970
Name: Cantidad a pedir, Length: 1998, dtype: float64

In [ ]:
X_test

array([[ 1.36974518,  0.48981483,  0.60531265, -0.40064892],
       [-0.61664002,  0.55191461,  1.10213909, -0.01116027],
       [-0.18752545, -1.25428262,  1.67296793,  0.37832837],
       ...,
       [ 1.50816923,  0.00703908, -0.29401647,  0.37832837],
       [-0.74814288,  0.75852562, -0.36373658, -0.40064892],
       [-0.91425174, -0.32863034,  1.51578173, -0.40064892]])

In [ ]:
nuevo = model.predict(np.array(sc.transform([[38,	4.8,	17.8,	0.3]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
nuevo

array([[256.99216]], dtype=float32)

# **Punto de Reorden**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/simulacion_eoq.xlsx",sheet_name="Sheet1")
data


D          K         h  L  Cantidad a pedir  Punto de reorden
0     602  53.193988  4.803646  5        115.467304          7.850101
1     935  65.869443  1.828454  2        259.549855         53.151016
2     848  61.015955  3.847163  2        164.007729         55.922705
3     770  75.765259  3.969524  4        171.445553        165.425592
4     606  55.118354  2.992482  4        149.411372         33.418055
...   ...        ...       ... ..               ...               ...
9985  556  55.581834  3.269109  6        137.500443         35.989359
9986  611  72.051740  1.716667  2        226.472121         89.639394
9987  504  67.693537  2.971393  2        151.538789         98.767265
9988  909  61.165752  4.494511  9        157.293176          1.754837
9989  913  82.108971  4.093853  2        191.372515        103.647361

[9990 rows x 6 columns]

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 94.3350 - mae: 7.7544
Error:97.62512969970703, Métrica: 7.820370674133301


In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D","K","h","L"]]
y = data["Punto de reorden"]
X.shape

(9990, 4)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(4,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(32,activation = "relu"))
model.add(Dense(32,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
optimizer = Adam(learning_rate=0.001)  # Reducimos la tasa de aprendizaje
model.compile(optimizer=optimizer, loss="mae", metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 1000
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52.6904 - mae: 52.6904
Error:52.321292877197266, Métrica: 52.321292877197266


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


Predicciones      Reales
0       100.063194   94.194536
1        79.656593   94.984712
2        63.698524   69.714385
3       104.585686  206.466848
4       135.464584  218.353389
...            ...         ...
1993     74.597130   97.889766
1994    168.995865   66.220356
1995    120.064339  186.683519
1996     97.466316   80.515346
1997     70.560776   34.292548

[1998 rows x 2 columns]

In [ ]:
y_test

4022     94.194536
5412     94.984712
487      69.714385
39      206.466848
6795    218.353389
           ...    
7292     97.889766
7710     66.220356
4094    186.683519
3944     80.515346
8256     34.292548
Name: Punto de reorden, Length: 1998, dtype: float64

In [ ]:
X_test

array([[ 1.36974518,  0.48981483,  0.60531265, -0.40064892],
       [-0.61664002,  0.55191461,  1.10213909, -0.01116027],
       [-0.18752545, -1.25428262,  1.67296793,  0.37832837],
       ...,
       [ 1.50816923,  0.00703908, -0.29401647,  0.37832837],
       [-0.74814288,  0.75852562, -0.36373658, -0.40064892],
       [-0.91425174, -0.32863034,  1.51578173, -0.40064892]])

In [ ]:
nuevo = model.predict(np.array(sc.transform([[659,	49.38,	0.07,	2]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
nuevo

array([[155.3974]], dtype=float32)