# **Pedido 1**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/Modelos de inventarios.xlsx",sheet_name="EOQ_area_max")
data

articulo.1  articulo.2  articulo.3  D1  D2  D3  K1  K2  K3   h1   h2   h3  \
0            1           2           3   2   4   4  10   5  15  0.3  0.1  0.2   
1            1           2           3   3   2   9  11  16   9  0.4  0.7  0.7   
2            1           2           3   3   3   4  16   7  18  0.7  0.7  0.2   
3            1           2           3   9  10   3   8  19   7  0.4  0.6  0.4   
4            1           2           3   8   4   7  17  13  16  0.3  0.2  0.3   
..         ...         ...         ...  ..  ..  ..  ..  ..  ..  ...  ...  ...   
95           1           2           3   4   9   4  15  18  16  0.3  0.5  0.5   
96           1           2           3   6   4   7   7  14  15  0.7  0.7  0.3   
97           1           2           3   9   8   4   5  18  18  0.1  0.5  0.4   
98           1           2           3   8   2   9  17  12   8  0.8  0.7  0.1   
99           1           2           3   5  10   4  16   6   8  0.6  0.6  0.8   

    a1  a2  a3   A  pedido_1  pedido_2  pedido_3  area_total  
0    1   1   1  25      6.34      7.09     11.57      24.999  
1    5   4   3  65      4.45      4.59      8.12      64.956  
2    3   4   1  46      6.10      3.62     13.20      45.993  
3    5   5   5  72      4.58      7.34      2.47      71.962  
4    4   2   4  74      7.90      6.83      7.17      73.957  
..  ..  ..  ..  ..       ...       ...       ...         ...  
95   2   4   2  50      5.75      6.73      5.78      49.983  
96   2   2   3  25      3.01      3.48      4.00      24.995  
97   4   2   5  43      2.98      7.22      3.33      42.987  
98   4   2   4  26      3.20      1.88      2.36      26.000  
99   1   5   3  40      9.03      4.02      3.62      39.984  

[100 rows x 20 columns]

In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D1",	"D2",	"D3",	"K1",	"K2",	"K3",	"h1",	"h2",	"h3",	"a1",	"a2",	"a3",	"A"]]
y = data["pedido_1"]
X.shape

(100, 13)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(13,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(16,activation = "relu"))
model.add(Dense(16,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
model.compile(optimizer="adam",loss = "mse",metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 1000
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 9.8919 - mae: 1.9772
Error:9.891912460327148, Métrica: 1.9771907329559326


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


Predicciones  Reales
0       4.444620    7.35
1       6.315495    5.61
2       3.163736    4.56
3      11.818093    9.52
4       4.305325    5.98
5       9.948009    9.95
6       3.424381    1.68
7       2.536403    4.05
8      15.806070   10.61
9       7.971040    6.34
10      6.436133    8.00
11      3.090792    3.18
12      4.307048    5.07
13      1.797972    1.65
14      4.130050    5.21
15      7.810310    7.90
16      4.435040    6.68
17      5.995762    5.72
18     15.673211   26.87
19      9.745678    6.72

In [ ]:
y_test

83     7.35
53     5.61
70     4.56
45     9.52
44     5.98
39     9.95
22     1.68
80     4.05
10    10.61
0      6.34
18     8.00
30     3.18
73     5.07
33     1.65
90     5.21
4      7.90
76     6.68
77     5.72
12    26.87
31     6.72
Name: pedido_1, dtype: float64

In [ ]:
X_test

array([[ 1.47849781,  0.89192228, -1.1998072 , -1.44220234, -0.92965474,
        -0.73837735, -0.65103077,  0.26919095,  1.2424803 ,  1.54860717,
        -0.77249749,  0.37796447,  1.09363479],
       [-1.04576675, -1.12752439, -0.22699055,  0.64794598, -0.48162836,
         0.85811422, -1.057925  ,  1.34595476,  1.63691849, -1.33252245,
         0.6989263 ,  0.37796447, -1.39682067],
       [-1.04576675,  1.56507116, -1.52407942,  1.06597564, -0.92965474,
        -0.9379388 , -1.057925  , -0.80757285,  0.45360392,  0.82832477,
         1.43463819,  1.13389342, -0.15159294],
       [ 0.75727937,  1.22849672, -1.52407942,  0.64794598, -1.15366793,
        -1.13750025, -1.057925  , -0.26919095,  1.63691849, -0.61224005,
        -0.77249749, -1.88982237, -0.36815429],
       [-1.04576675, -1.12752439,  0.09728167, -1.2331875 , -1.37768112,
        -1.13750025,  0.16275769,  0.26919095, -1.12414884, -1.33252245,
        -0.03678559,  1.13389342, -0.63885597],
       [ 1.47849781, -0.454375

In [ ]:
nuevo = model.predict(np.array(sc.fit_transform([[2,	4	,4	,10,	5,	15,	0.3,	0.1,	0.2	,1	,1	,1,	25]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


In [ ]:
nuevo

array([[2.4659033]], dtype=float32)

# **Pedido 2**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/Modelos de inventarios.xlsx",sheet_name="EOQ_area_max")
data

articulo.1  articulo.2  articulo.3  D1  D2  D3  K1  K2  K3   h1   h2   h3  \
0            1           2           3   2   4   4  10   5  15  0.3  0.1  0.2   
1            1           2           3   3   2   9  11  16   9  0.4  0.7  0.7   
2            1           2           3   3   3   4  16   7  18  0.7  0.7  0.2   
3            1           2           3   9  10   3   8  19   7  0.4  0.6  0.4   
4            1           2           3   8   4   7  17  13  16  0.3  0.2  0.3   
..         ...         ...         ...  ..  ..  ..  ..  ..  ..  ...  ...  ...   
95           1           2           3   4   9   4  15  18  16  0.3  0.5  0.5   
96           1           2           3   6   4   7   7  14  15  0.7  0.7  0.3   
97           1           2           3   9   8   4   5  18  18  0.1  0.5  0.4   
98           1           2           3   8   2   9  17  12   8  0.8  0.7  0.1   
99           1           2           3   5  10   4  16   6   8  0.6  0.6  0.8   

    a1  a2  a3   A  pedido_1  pedido_2  pedido_3  area_total  
0    1   1   1  25      6.34      7.09     11.57      24.999  
1    5   4   3  65      4.45      4.59      8.12      64.956  
2    3   4   1  46      6.10      3.62     13.20      45.993  
3    5   5   5  72      4.58      7.34      2.47      71.962  
4    4   2   4  74      7.90      6.83      7.17      73.957  
..  ..  ..  ..  ..       ...       ...       ...         ...  
95   2   4   2  50      5.75      6.73      5.78      49.983  
96   2   2   3  25      3.01      3.48      4.00      24.995  
97   4   2   5  43      2.98      7.22      3.33      42.987  
98   4   2   4  26      3.20      1.88      2.36      26.000  
99   1   5   3  40      9.03      4.02      3.62      39.984  

[100 rows x 20 columns]

In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D1",	"D2",	"D3",	"K1",	"K2",	"K3",	"h1",	"h2",	"h3",	"a1",	"a2",	"a3",	"A","pedido_1"]]
y = data["pedido_2"]
X.shape

(100, 14)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(14,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(16,activation = "relu"))
model.add(Dense(16,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
model.compile(optimizer="adam",loss = "mse",metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 1000
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 3.5603 - mae: 1.5211
Error:3.5603363513946533, Métrica: 1.5211135149002075


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


Predicciones  Reales
0       9.243325   10.69
1       2.893282    1.88
2       5.725235    5.08
3       9.413754    7.87
4       8.747764    3.44
5       7.922890    9.89
6       3.116036    4.53
7      11.711286   11.06
8       5.288656    5.09
9       7.981933    7.09
10      3.872784    6.42
11      2.004108    3.66
12      5.786242    6.49
13      6.599006    6.98
14      4.931184    5.43
15      5.186551    6.83
16      7.642663    5.38
17      2.891526    5.52
18      7.996397    5.95
19      3.814952    2.84

In [ ]:
y_test

83    10.69
53     1.88
70     5.08
45     7.87
44     3.44
39     9.89
22     4.53
80    11.06
10     5.09
0      7.09
18     6.42
30     3.66
73     6.49
33     6.98
90     5.43
4      6.83
76     5.38
77     5.52
12     5.95
31     2.84
Name: pedido_2, dtype: float64

In [ ]:
X_test

array([[ 1.47849781,  0.89192228, -1.1998072 , -1.44220234, -0.92965474,
        -0.73837735, -0.65103077,  0.26919095,  1.2424803 ,  1.54860717,
        -0.77249749,  0.37796447,  1.09363479,  0.04254035],
       [-1.04576675, -1.12752439, -0.22699055,  0.64794598, -0.48162836,
         0.85811422, -1.057925  ,  1.34595476,  1.63691849, -1.33252245,
         0.6989263 ,  0.37796447, -1.39682067, -0.29778246],
       [-1.04576675,  1.56507116, -1.52407942,  1.06597564, -0.92965474,
        -0.9379388 , -1.057925  , -0.80757285,  0.45360392,  0.82832477,
         1.43463819,  1.13389342, -0.15159294, -0.50314968],
       [ 0.75727937,  1.22849672, -1.52407942,  0.64794598, -1.15366793,
        -1.13750025, -1.057925  , -0.26919095,  1.63691849, -0.61224005,
        -0.77249749, -1.88982237, -0.36815429,  0.46696593],
       [-1.04576675, -1.12752439,  0.09728167, -1.2331875 , -1.37768112,
        -1.13750025,  0.16275769,  0.26919095, -1.12414884, -1.33252245,
        -0.03678559,  1.13

In [ ]:
nuevo = model.predict(np.array(sc.fit_transform([[2,	4	,4	,10,	5,	15,	0.3,	0.1,	0.2	,1	,1	,1,	25,6.34]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


In [ ]:
nuevo

array([[3.2365773]], dtype=float32)

# **Pedido 3**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/Modelos de inventarios.xlsx",sheet_name="EOQ_area_max")
data

articulo.1  articulo.2  articulo.3  D1  D2  D3  K1  K2  K3   h1   h2   h3  \
0            1           2           3   2   4   4  10   5  15  0.3  0.1  0.2   
1            1           2           3   3   2   9  11  16   9  0.4  0.7  0.7   
2            1           2           3   3   3   4  16   7  18  0.7  0.7  0.2   
3            1           2           3   9  10   3   8  19   7  0.4  0.6  0.4   
4            1           2           3   8   4   7  17  13  16  0.3  0.2  0.3   
..         ...         ...         ...  ..  ..  ..  ..  ..  ..  ...  ...  ...   
95           1           2           3   4   9   4  15  18  16  0.3  0.5  0.5   
96           1           2           3   6   4   7   7  14  15  0.7  0.7  0.3   
97           1           2           3   9   8   4   5  18  18  0.1  0.5  0.4   
98           1           2           3   8   2   9  17  12   8  0.8  0.7  0.1   
99           1           2           3   5  10   4  16   6   8  0.6  0.6  0.8   

    a1  a2  a3   A  pedido_1  pedido_2  pedido_3  area_total  
0    1   1   1  25      6.34      7.09     11.57      24.999  
1    5   4   3  65      4.45      4.59      8.12      64.956  
2    3   4   1  46      6.10      3.62     13.20      45.993  
3    5   5   5  72      4.58      7.34      2.47      71.962  
4    4   2   4  74      7.90      6.83      7.17      73.957  
..  ..  ..  ..  ..       ...       ...       ...         ...  
95   2   4   2  50      5.75      6.73      5.78      49.983  
96   2   2   3  25      3.01      3.48      4.00      24.995  
97   4   2   5  43      2.98      7.22      3.33      42.987  
98   4   2   4  26      3.20      1.88      2.36      26.000  
99   1   5   3  40      9.03      4.02      3.62      39.984  

[100 rows x 20 columns]

In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D1",	"D2",	"D3",	"K1",	"K2",	"K3",	"h1",	"h2",	"h3",	"a1",	"a2",	"a3",	"A","pedido_1","pedido_2"]]
y = data["pedido_3"]
X.shape

(100, 15)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(15,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(16,activation = "relu"))
model.add(Dense(16,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
model.compile(optimizer="adam",loss = "mse",metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 1000
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 3.2267 - mae: 1.3133
Error:3.226736545562744, Métrica: 1.3132765293121338


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


Predicciones  Reales
0       3.431002    3.96
1       4.085304    3.72
2       3.671424    1.47
3       4.727335    2.64
4       3.097626    5.13
5      11.146212    5.69
6       3.464120    3.27
7       7.167640    6.51
8       4.710855    4.95
9      11.498470   11.57
10     11.605109   12.37
11      3.058127    1.78
12      5.448244    4.99
13      2.068436    2.89
14      7.046382    5.60
15      5.688051    7.17
16      2.525758    5.14
17      7.926490    5.67
18     10.681746   11.73
19     10.398693   10.66

In [ ]:
y_test

83     3.96
53     3.72
70     1.47
45     2.64
44     5.13
39     5.69
22     3.27
80     6.51
10     4.95
0     11.57
18    12.37
30     1.78
73     4.99
33     2.89
90     5.60
4      7.17
76     5.14
77     5.67
12    11.73
31    10.66
Name: pedido_3, dtype: float64

In [ ]:
X_test

array([[ 1.47849781,  0.89192228, -1.1998072 , -1.44220234, -0.92965474,
        -0.73837735, -0.65103077,  0.26919095,  1.2424803 ,  1.54860717,
        -0.77249749,  0.37796447,  1.09363479,  0.04254035,  1.92829273],
       [-1.04576675, -1.12752439, -0.22699055,  0.64794598, -0.48162836,
         0.85811422, -1.057925  ,  1.34595476,  1.63691849, -1.33252245,
         0.6989263 ,  0.37796447, -1.39682067, -0.29778246, -1.77769744],
       [-1.04576675,  1.56507116, -1.52407942,  1.06597564, -0.92965474,
        -0.9379388 , -1.057925  , -0.80757285,  0.45360392,  0.82832477,
         1.43463819,  1.13389342, -0.15159294, -0.50314968, -0.43159432],
       [ 0.75727937,  1.22849672, -1.52407942,  0.64794598, -1.15366793,
        -1.13750025, -1.057925  , -0.26919095,  1.63691849, -0.61224005,
        -0.77249749, -1.88982237, -0.36815429,  0.46696593,  0.74203935],
       [-1.04576675, -1.12752439,  0.09728167, -1.2331875 , -1.37768112,
        -1.13750025,  0.16275769,  0.26919095, 

In [ ]:
nuevo = model.predict(np.array(sc.fit_transform([[2,	4	,4	,10,	5,	15,	0.3,	0.1,	0.2	,1	,1	,1,	25,6.34,7.09]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step


In [ ]:
nuevo

array([[1.8984476]], dtype=float32)

# **Area total**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/Modelos de inventarios.xlsx",sheet_name="EOQ_area_max")
data

articulo.1  articulo.2  articulo.3  D1  D2  D3  K1  K2  K3   h1   h2   h3  \
0            1           2           3   2   4   4  10   5  15  0.3  0.1  0.2   
1            1           2           3   3   2   9  11  16   9  0.4  0.7  0.7   
2            1           2           3   3   3   4  16   7  18  0.7  0.7  0.2   
3            1           2           3   9  10   3   8  19   7  0.4  0.6  0.4   
4            1           2           3   8   4   7  17  13  16  0.3  0.2  0.3   
..         ...         ...         ...  ..  ..  ..  ..  ..  ..  ...  ...  ...   
95           1           2           3   4   9   4  15  18  16  0.3  0.5  0.5   
96           1           2           3   6   4   7   7  14  15  0.7  0.7  0.3   
97           1           2           3   9   8   4   5  18  18  0.1  0.5  0.4   
98           1           2           3   8   2   9  17  12   8  0.8  0.7  0.1   
99           1           2           3   5  10   4  16   6   8  0.6  0.6  0.8   

    a1  a2  a3   A  pedido_1  pedido_2  pedido_3  area_total  
0    1   1   1  25      6.34      7.09     11.57      24.999  
1    5   4   3  65      4.45      4.59      8.12      64.956  
2    3   4   1  46      6.10      3.62     13.20      45.993  
3    5   5   5  72      4.58      7.34      2.47      71.962  
4    4   2   4  74      7.90      6.83      7.17      73.957  
..  ..  ..  ..  ..       ...       ...       ...         ...  
95   2   4   2  50      5.75      6.73      5.78      49.983  
96   2   2   3  25      3.01      3.48      4.00      24.995  
97   4   2   5  43      2.98      7.22      3.33      42.987  
98   4   2   4  26      3.20      1.88      2.36      26.000  
99   1   5   3  40      9.03      4.02      3.62      39.984  

[100 rows x 20 columns]

In [ ]:
len(data)
data = data.dropna()

In [ ]:
X = data [["D1",	"D2",	"D3",	"K1",	"K2",	"K3",	"h1",	"h2",	"h3",	"a1",	"a2",	"a3",	"A","pedido_1","pedido_2","pedido_3"]]
y = data["area_total"]
X.shape

(100, 16)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Escalar los datos (X)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
## Crear la red neuronal

import tensorflow as tf

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
## Red neuronal
model = Sequential()
model.add(Dense(16,activation = "relu",input_shape = (X_train.shape[1],)))
model.add(Dense(16,activation = "relu"))
model.add(Dense(16,activation = "relu"))
model.add(Dense(1))    ## si NN para predicción solo una neurona en la capa de salida

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
## Compilar la red
model.compile(optimizer="adam",loss = "mse",metrics=["mae"])

In [ ]:
## Entrenar la red
epocas = 1000
history = model.fit(X_train,y_train,epochs = epocas,validation_split = 0.1, verbose = 10)

Epoch 1/1000
Epoch 2/1000
Epoch 3/1000
Epoch 4/1000
Epoch 5/1000
Epoch 6/1000
Epoch 7/1000
Epoch 8/1000
Epoch 9/1000
Epoch 10/1000
Epoch 11/1000
Epoch 12/1000
Epoch 13/1000
Epoch 14/1000
Epoch 15/1000
Epoch 16/1000
Epoch 17/1000
Epoch 18/1000
Epoch 19/1000
Epoch 20/1000
Epoch 21/1000
Epoch 22/1000
Epoch 23/1000
Epoch 24/1000
Epoch 25/1000
Epoch 26/1000
Epoch 27/1000
Epoch 28/1000
Epoch 29/1000
Epoch 30/1000
Epoch 31/1000
Epoch 32/1000
Epoch 33/1000
Epoch 34/1000
Epoch 35/1000
Epoch 36/1000
Epoch 37/1000
Epoch 38/1000
Epoch 39/1000
Epoch 40/1000
Epoch 41/1000
Epoch 42/1000
Epoch 43/1000
Epoch 44/1000
Epoch 45/1000
Epoch 46/1000
Epoch 47/1000
Epoch 48/1000
Epoch 49/1000
Epoch 50/1000
Epoch 51/1000
Epoch 52/1000
Epoch 53/1000
Epoch 54/1000
Epoch 55/1000
Epoch 56/1000
Epoch 57/1000
Epoch 58/1000
Epoch 59/1000
Epoch 60/1000
Epoch 61/1000
Epoch 62/1000
Epoch 63/1000
Epoch 64/1000
Epoch 65/1000
Epoch 66/1000
Epoch 67/1000
Epoch 68/1000
Epoch 69/1000
Epoch 70/1000
Epoch 71/1000
Epoch 72/1000
E

In [ ]:
## Evaluar el modelo
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Error:{test_loss}, Métrica: {test_mae}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 91.3501 - mae: 7.7206
Error:91.35005187988281, Métrica: 7.720639228820801


In [ ]:
## Predicciones
predicciones = model.predict(X_test)
comparacion = pd.DataFrame(predicciones,columns = ["Predicciones"])
comparacion["Reales"] = y_test.values
comparacion

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


Predicciones  Reales
0      63.389858  73.984
1      27.465395  27.997
2      47.925682  50.992
3      46.768253  46.954
4      28.648151  41.937
5      61.376316  70.998
6      38.937607  34.992
7      60.719337  72.994
8      61.686455  76.949
9      14.519006  24.999
10     45.089748  59.987
11     22.051596  23.998
12     47.214207  45.995
13     26.597807  27.999
14     49.939816  53.983
15     60.425133  73.957
16     49.429359  65.978
17     46.905716  49.993
18     78.517265  73.963
19     63.060677  76.993

In [ ]:
y_test

83    73.984
53    27.997
70    50.992
45    46.954
44    41.937
39    70.998
22    34.992
80    72.994
10    76.949
0     24.999
18    59.987
30    23.998
73    45.995
33    27.999
90    53.983
4     73.957
76    65.978
77    49.993
12    73.963
31    76.993
Name: area_total, dtype: float64

In [ ]:
X_test

array([[ 1.47849781,  0.89192228, -1.1998072 , -1.44220234, -0.92965474,
        -0.73837735, -0.65103077,  0.26919095,  1.2424803 ,  1.54860717,
        -0.77249749,  0.37796447,  1.09363479,  0.04254035,  1.92829273,
        -0.5855281 ],
       [-1.04576675, -1.12752439, -0.22699055,  0.64794598, -0.48162836,
         0.85811422, -1.057925  ,  1.34595476,  1.63691849, -1.33252245,
         0.6989263 ,  0.37796447, -1.39682067, -0.29778246, -1.77769744,
        -0.66005832],
       [-1.04576675,  1.56507116, -1.52407942,  1.06597564, -0.92965474,
        -0.9379388 , -1.057925  , -0.80757285,  0.45360392,  0.82832477,
         1.43463819,  1.13389342, -0.15159294, -0.50314968, -0.43159432,
        -1.3587792 ],
       [ 0.75727937,  1.22849672, -1.52407942,  0.64794598, -1.15366793,
        -1.13750025, -1.057925  , -0.26919095,  1.63691849, -0.61224005,
        -0.77249749, -1.88982237, -0.36815429,  0.46696593,  0.74203935,
        -0.99544434],
       [-1.04576675, -1.12752439,  0

In [ ]:
nuevo = model.predict(np.array(sc.fit_transform([[2,	4	,4	,10,	5,	15,	0.3,	0.1,	0.2	,1	,1	,1,	25,6.34,7.09,11.57]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


In [ ]:
nuevo

array([[27.595299]], dtype=float32)